ndex:
  network: da832549-f6a3-11e8-aaa6-0ac135e8bacf
search_terms:
- "ACTRT1"
- "ADAM7"
- "ADAMDEC1"
- "ADH1A"
- "ADH1B"
- "ADH1C"
- "ANGPT1"
- "APCS"
- "BAGE2"
- "BMP5"
- "BRAF"
- "BRINP3"
- "C6"
- "C8B"
- "CA1"
- "CACNG3"
- "CADM2"
- "CAPSL"
- "CAPZA3"
- "CCL8"
- "CD1C"
- "CDH6"
- "CDKN2A"
- "CDR1"
- "CFHR2"
- "CFHR5"
- "CLEC5A"
- "CLVS1"
- "CRISP2"
- "CRISP3"
- "CRP"
- "CYLC2"
- "CYP2C18"
- "CYP2C19"
- "CYP2C8"
- "CYP2C9"
- "DAB1"
- "DCC"
- "DCDC1"
- "DEFA6"
- "DEFB115"
- "DEFB118"
- "DEFB119"
- "DNAJC5B"
- "DPPA2"
- "DPPA3"
- "DPPA5"
- "DPRX"
- "DUSP22"
- "DYNAP"
- "FAM170A"
- "FAM19A1"
- "FAM83B"
- "FCER1A"
- "FGF12"
- "FHIT"
- "FUT9"
- "FYB2"
- "GABRG1"
- "GALNT13"
- "GALNT17"
- "GALP"
- "GFRAL"
- "GIMAP1"
- "GIMAP6"
- "GIMAP7"
- "GK2"
- "GLRB"
- "GLYATL1"
- "GML"
- "GNGT2"
- "GPX5"
- "GRM3"
- "GYPB"
- "HBG2"
- "HCRTR2"
- "HIST1H2AA"
- "HNF4G"
- "HTN3"
- "IL17A"
- "IL36A"
- "IL36B"
- "IL37"
- "IL7R"
- "ISX"
- "KCNB2"
- "KHDRBS2"
- "LACRT"
- "LAMP5"
- "LCE1B"
- "LCE1E"
- "LILRA1"
- "LILRB4"
- "LINC01559"
- "LLCFC1"
- "LRRC3B"
- "LRTM1"
- "LUZP2"
- "MAGEA10"
- "MAGEC1"
- "MARCO"
- "MMP26"
- "MRAP2"
- "MRGPRX1"
- "MSR1"
- "MUC7"
- "MYF6"
- "MYL1"
- "NEUROD4"
- "NMS"
- "NPSR1"
- "NRAS"
- "NREP"
- "NRXN1"
- "NRXN3"
- "OPRPN"
- "OR10K2"
- "OR13C8"
- "OR2F1"
- "OR2L2"
- "OR2M3"
- "OR4C13"
- "OR4E2"
- "OR4K1"
- "OR4K2"
- "OR4M1"
- "OR4M2"
- "OR4N2"
- "OR51B5"
- "OR52A5"
- "OR52J3"
- "OR5D13"
- "OR9A4"
- "PAK5"
- "PARM1"
- "PCED1B"
- "PCP4"
- "PCP4L1"
- "PDE1A"
- "PENK"
- "PGK2"
- "PPP6C"
- "PRB2"
- "PRB3"
- "PRB4"
- "PRRG3"
- "PRSS1"
- "PRSS37"
- "PSG5"
- "PSG9"
- "PTEN"
- "PTH2"
- "RAB27B"
- "RAC1"
- "RBFOX1"
- "REG3G"
- "RETNLB"
- "RGS7"
- "RIT2"
- "RNF152"
- "RPL22"
- "S100A12"
- "S100A8"
- "SAMD7"
- "SDR16C5"
- "SERPINB3"
- "SERPINB4"
- "SERPINB7"
- "SERPINI2"
- "SGCZ"
- "SLC10A2"
- "SLC30A8"
- "SMR3A"
- "SMR3B"
- "SNCAIP"
- "SPATA8"
- "SPOCK3"
- "SPRR2G"
- "ST6GAL2"
- "SYNDIG1"
- "SYT10"
- "TAS2R38"
- "TAS2R60"
- "TLL1"
- "TMEM176A"
- "TP53"
- "TP63"
- "TPTE"
- "TPTE2"
- "TRAT1"
- "TRHR"
- "TSHB"
- "UGT2B28"
- "UGT2B4"
- "ZBED2"
- "ZMAT4"
- "ZNF385D"
- "ALW-II-38-3"
- "AZ-628"
- "AZD7762"
- "BMS-536924"
- "Baicalein"
- "Dabrafenib"
- "Dasatinib"
- "GDC-0879"
- "GM6001"
- "GSK 690693"
- "IKK16"
- "Imatinib"
- "KW2449"
- "L-779450"
- "Lestaurtinib"
- "Motesanib"
- "NVP-TAE684"
- "Nilotinib"
- "Nutlin 3a"
- "PF-3758309"
- "PLX-4720"
- "PRT062607"
- "Pazopanib"
- "R406"
- "RAF 265"
- "Regorafenib"
- "SB 203580"
- "SB590885"
- "Sorafenib"
- "Staurosporine"
- "Sunitinib"
- "TAK-632"
- "Vemurafenib"
