ndex:
  network: 8d1330ca-f6a2-11e8-aaa6-0ac135e8bacf
search_terms:
- "ACER1"
- "ACTL9"
- "ACVR1B"
- "ACVR2A"
- "ADAT2"
- "APTX"
- "ARID1A"
- "ATG101"
- "ATP5MC3"
- "ATP5MD"
- "ATP6V1F"
- "B9D2"
- "BAGE2"
- "BDNF"
- "BLID"
- "BPIFA1"
- "CCL24"
- "CCL3"
- "CCND2"
- "CD33"
- "CD86"
- "CDC42SE2"
- "CDKN2A"
- "CETN1"
- "CHCHD7"
- "CIDEA"
- "CLEC4A"
- "CNBD1"
- "CNIH3"
- "COPS9"
- "COX4I2"
- "COX7B2"
- "CSTA"
- "CTSG"
- "DCAF4L2"
- "DEFB119"
- "DRGX"
- "DSCR4"
- "EBPL"
- "ELMOD1"
- "ELOC"
- "ENY2"
- "FAM107A"
- "FAM19A5"
- "FCGR3B"
- "FGF6"
- "FHIT"
- "FOLH1"
- "GABARAPL1"
- "GABRB1"
- "GAST"
- "GDF6"
- "GDNF"
- "GFRA3"
- "GLI3"
- "GLO1"
- "GNAS"
- "GNRH2"
- "GPM6B"
- "GPR26"
- "GUCA1C"
- "H2AFV"
- "H2AFZ"
- "HCST"
- "HIST1H1B"
- "HIST1H1E"
- "HIST1H2BF"
- "HIST1H2BO"
- "HIST1H4D"
- "HIST1H4E"
- "HIST1H4G"
- "HIST2H2AC"
- "HS3ST2"
- "HSPB8"
- "HTN3"
- "IAPP"
- "IL21"
- "IL9"
- "IRF6"
- "IRX1"
- "IYD"
- "JAM2"
- "KCNA1"
- "KCNA6"
- "KLK15"
- "KRAS"
- "KRT4"
- "KRTAP1-3"
- "KRTAP12-3"
- "KRTAP19-2"
- "KRTAP22-1"
- "KRTAP4-1"
- "LCE1C"
- "LCE2C"
- "LCE5A"
- "MAGEB1"
- "MAGEB2"
- "MAP1LC3A"
- "MAP2K4"
- "MAP2K7"
- "MED10"
- "MEF2C"
- "MMP26"
- "MRPS36"
- "MRPS6"
- "MSRB3"
- "MT2A"
- "MTCP1"
- "MTRNR2L1"
- "NAA40"
- "NGF"
- "NNAT"
- "NPY1R"
- "NRN1"
- "NRXN1"
- "NRXN2"
- "NRXN3"
- "NTF3"
- "NTM"
- "NUDCD2"
- "OCA2"
- "OR4P4"
- "OR4S2"
- "OR5D13"
- "OR5M11"
- "OR7D4"
- "OR8H2"
- "P2RY6"
- "PCMTD1"
- "PI15"
- "PMEPA1"
- "PMP22"
- "PPP1R1C"
- "PRB4"
- "PRL"
- "PRM1"
- "PROP1"
- "PRR15L"
- "PRSS1"
- "PSG6"
- "RAP1B"
- "RARRES3"
- "RBFOX1"
- "RBM10"
- "RETNLB"
- "RFK"
- "RNF43"
- "RPL11"
- "RPL28"
- "RPLP2"
- "RPS28"
- "RRAS2"
- "RSPO1"
- "RYBP"
- "S100A3"
- "S100A4"
- "SCN3B"
- "SEC14L3"
- "SH3BGRL3"
- "SLC35G5"
- "SMAD3"
- "SMAD4"
- "SNRPE"
- "SOX5"
- "SPANXC"
- "SPATA8"
- "SPI1"
- "SPRR2A"
- "SST"
- "ST6GAL2"
- "STK11"
- "TGFBR1"
- "TGFBR2"
- "THYN1"
- "TMEM215"
- "TMEM52"
- "TMSB10"
- "TP53"
- "TPO"
- "TPRG1"
- "TPSD1"
- "TPTE"
- "TPTE2"
- "TRH"
- "TRIM48"
- "TSPAN2"
- "U2AF1"
- "UBE2D4"
- "UQCR11"
- "VCX"
- "VPS25"
- "ZFP36L2"
- "ZFP42"
- "ZIM2"
- "ZNF576"
- "ZNF814"
- "ZNRF4"
- "5z-7-oxozeaenol"
- "AZD 5438"
- "Alvocidib"
- "Bortezomib"
- "Canertinib"
- "Crizotinib"
- "D 4476"
- "Dabrafenib"
- "Dasatinib"
- "Dorsomorphin"
- "EW-7197"
- "Fedratinib"
- "GM6001"
- "GSK1838705A"
- "HG-9-91-01"
- "KW2449"
- "Ki20227"
- "LDN-193189"
- "LY2109761"
- "Lestaurtinib"
- "NVP-TAE684"
- "Neratinib"
- "Nintedanib"
- "Nutlin 3a"
- "PKC412"
- "PLX-4720"
- "Palbociclib"
- "Pazopanib"
- "R406"
- "SB202190"
- "SB525334"
- "SNS-032"
- "SP600125"
- "Staurosporine"
- "Sunitinib"
