language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libssl1.0.0
install:
  - wget "https://github.com/RuleWorld/bionetgen/releases/download/BioNetGen-2.4.0/BioNetGen-2.4.0-Linux.tgz" -O bionetgen.tar.gz -nv
  - tar xzf bionetgen.tar.gz
  - export BNGPATH=`pwd`/BioNetGen-2.4.0
  - pip install git+https://github.com/sorgerlab/indra.git
  - pip uninstall enum34
  - pip install git+https://github.com/indralab/indra_db.git
  - pip install git+https://github.com/indralab/indra_reading.git
  - pip install git+https://github.com/sorgerlab/bioagents.git
  - git clone https://github.com/indralab/ui_util.git
  - cd ui_util/indralab_auth_tools
  - pip install .
  - cd ../indralab_web_templates
  - pip install .
  - cd ../..
  - pip install .[test]
before_script:
  # Create a test database.
  - psql -c 'create database emmaadb_test;' -U postgres
script:
  - export AWS_DEFAULT_REGION='us-east-1'
  - export NOSEATTR="!notravis";
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
      export NOSEATTR="!nonpublic,$NOSEATTR";
    fi
  - nosetests -v -a $NOSEATTR emmaa/tests/test_s3.py
  - nosetests -v -a $NOSEATTR --ignore-files='.*test_s3.py' --with-coverage
    --cover-inclusive --cover-package=emmaa -w emmaa/tests 
after_success:
  - coveralls
