language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libssl1.0.0
install:
  - pip install git+https://github.com/sorgerlab/indra.git
  - pip install git+https://github.com/indralab/indra_db.git
  - pip install git+https://github.com/indralab/ui_util.git
  - pip install .[test]
before_script:
  # Create a test database.
  - psql -c 'create database emmaadb_test;' -U postgres
script:
  - export AWS_DEFAULT_REGION='us-east-1'
  - export NOSEATTR="!notravis";
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
      export NOSEATTR="!nonpublic,$NOSEATTR";
    fi
  - nosetests -v -a $NOSEATTR --with-coverage --cover-inclusive
    --cover-package=emmaa -w emmaa/tests
after_success:
  - coveralls
