language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
install:
  - pip install git+https://github.com/sorgerlab/indra.git
  - pip install git+https://github.com/indralab/indra_db.git
  - pip install .[test]
script:
  - export AWS_DEFAULT_REGION='us-east-1'
  - nosetests -v --with-coverage --cover-inclusive --cover-package=emmaa -w emmaa/tests
after_success:
  - coveralls
