ndex:
  network: caa8c3f6-f6a3-11e8-aaa6-0ac135e8bacf
search_terms:
- "A1CF"
- "ALOX5AP"
- "AR"
- "BAGE2"
- "BANF2"
- "BCLAF1"
- "BOLA2"
- "BRAF"
- "CA2"
- "CACNG3"
- "CCL11"
- "CCL23"
- "CCND2"
- "CD1A"
- "CD1B"
- "CD1E"
- "CD40LG"
- "CD48"
- "CDH11"
- "CDH8"
- "CDK12"
- "CDK5"
- "CDKN1A"
- "CDKN1B"
- "CELA3B"
- "CHEK2"
- "CLEC1A"
- "CLEC9A"
- "CNTN6"
- "CNTNAP5"
- "COX7A1"
- "COX7A2"
- "COX7C"
- "CRYBB1"
- "CSDC2"
- "CST8"
- "CTNNA2"
- "CTNNB1"
- "CTSC"
- "CUL3"
- "CUX1"
- "CYP11B1"
- "CYTIP"
- "CYTL1"
- "DCAF4L2"
- "DCDC1"
- "DDI1"
- "DLX6"
- "EDIL3"
- "EFNA5"
- "EIF1AX"
- "ERF"
- "ERG"
- "ETV1"
- "ETV4"
- "FABP6"
- "FHIT"
- "FLRT2"
- "FOLR3"
- "FOXA1"
- "GABRB1"
- "GAD2"
- "GAST"
- "GNAS"
- "GNGT1"
- "GPATCH4"
- "GRIA1"
- "GRIN2A"
- "GUCA1A"
- "GYPB"
- "GYPC"
- "HCN1"
- "HIST1H1A"
- "HIST1H1C"
- "HIST1H2BC"
- "HIST1H2BN"
- "HIST1H3B"
- "HIST1H3C"
- "HIST1H3F"
- "HIST1H4H"
- "HIST2H2AC"
- "HIST2H2BE"
- "HIST2H2BF"
- "HIST2H4A"
- "HOXB13"
- "HOXD4"
- "HRAS"
- "HTR1E"
- "IDH1"
- "IFNA16"
- "IL17A"
- "JTB"
- "KCNE3"
- "KCTD16"
- "KDM6A"
- "KIF2B"
- "KLK2"
- "KLK3"
- "KLK8"
- "KRAS"
- "KRTAP1-5"
- "KRTAP13-3"
- "KRTAP19-6"
- "KRTAP23-1"
- "KRTAP9-4"
- "LCE1B"
- "LCE1C"
- "LCE2C"
- "LCE5A"
- "LEPROT"
- "LGALS14"
- "MACROD2"
- "MGP"
- "MORN4"
- "MRGPRX1"
- "MRPL14"
- "MRPL23"
- "MS4A13"
- "MSC"
- "MT-CO1"
- "MT-CO2"
- "MT-CYB"
- "MT-ND1"
- "MT-ND4"
- "MT-ND4L"
- "MT-ND5"
- "MUC4"
- "MYEOV"
- "MYL1"
- "NBPF1"
- "NEU2"
- "NHLH1"
- "NHLH2"
- "NKIRAS2"
- "NKX3-1"
- "NMUR2"
- "NPS"
- "NR2C2AP"
- "NRXN2"
- "NRXN3"
- "NTM"
- "NUDT11"
- "OR10Z1"
- "OR2M3"
- "OR4C13"
- "OR4C6"
- "OR4D5"
- "OR4N2"
- "OR4P4"
- "OR4S2"
- "OR5AS1"
- "PAEP"
- "PAQR4"
- "PAX5"
- "PAX6"
- "PCP4"
- "PDGFD"
- "PF4"
- "PFN2"
- "PI3"
- "PID1"
- "PIK3CA"
- "PIK3R1"
- "PMP22"
- "PPP1R14C"
- "PRM3"
- "PTEN"
- "PTH2"
- "PYHIN1"
- "RAB14"
- "RB1"
- "REEP1"
- "RHOA"
- "RNF152"
- "RNF181"
- "RPL11"
- "RPL22"
- "RPS5"
- "RYBP"
- "SELENOK"
- "SF3B5"
- "SMIM3"
- "SOX17"
- "SPOP"
- "SPRR1A"
- "TMPRSS2"
- "TNP1"
- "TP53"
- "TPD52L3"
- "TUBA3C"
- "UQCR11"
- "VAMP2"
- "VAPA"
- "XCL1"
- "YPEL3"
- "ZIC4"
- "ZMAT4"
- "(s)-CR8"
- "A66"
- "ALW-II-38-3"
- "AS-252424"
- "AS605240"
- "AT-7519"
- "AZ-628"
- "AZD-6482"
- "AZD7762"
- "Alpelisib"
- "Alvocidib"
- "BAY61-3606"
- "Bosutinib"
- "Buparlisib"
- "CAL-101"
- "CGP60474"
- "CGP74514A"
- "CUDC-907"
- "Celecoxib"
- "Chk2 inhibitor II"
- "Dabrafenib"
- "Dactolisib"
- "Dasatinib"
- "Dinaciclib"
- "Enzalutamide"
- "Foretinib"
- "GDC-0879"
- "GDC-0980"
- "GSK-J1"
- "GSK-J4"
- "GSK1059615"
- "GSK1838705A"
- "Gefitinib"
- "Go 6976"
- "HG-14-10-04"
- "Imatinib"
- "KIN001-111"
- "KIN001-135"
- "KW2449"
- "L-779450"
- "LY294002"
- "Lestaurtinib"
- "MK 1775"
- "Motesanib"
- "NU7441"
- "NVP-BGT226"
- "NVP-TAE226"
- "NVP-TAE684"
- "Neratinib"
- "Nilotinib"
- "Nutlin 3a"
- "Olomoucine II"
- "Omipalisib"
- "PF562271"
- "PHA-767491"
- "PHA-793887"
- "PI103"
- "PI3K-IN-1"
- "PIK-93"
- "PLX-4720"
- "Palbociclib"
- "Pazopanib"
- "Pictilisib"
- "Purvalanol A"
- "R406"
- "RAF 265"
- "RGB-286147"
- "Regorafenib"
- "Resveratrol"
- "Rigosertib"
- "SB 203580"
- "SB590885"
- "SNS-032"
- "Seliciclib"
- "Sorafenib"
- "Staurosporine"
- "Sulindac sulfide"
- "Sunitinib"
- "TAK-632"
- "TPCA-1"
- "Taselisib"
- "Torin1"
- "Torin2"
- "Vemurafenib"
- "XL147"
- "XL765"
- "XMD11-50"
- "ZSTK474"
