ndex:
  network: b56642b3-f6a3-11e8-aaa6-0ac135e8bacf
search_terms:
- "KRAS"
- "TP53"
- "STK11"
- "REG3A"
- "REG1A"
- "NRXN1"
- "REG1B"
- "TPTE"
- "KEAP1"
- "KRTAP20-2"
- "TGIF2LX"
- "REG3G"
- "DCAF4L2"
- "CDH10"
- "SNTG1"
- "KRTAP19-6"
- "PRSS1"
- "EGFR"
- "KRTAP6-1"
- "KRTAP19-5"
- "SPRR2G"
- "ZP4"
- "DRD3"
- "KRTAP8-1"
- "KRTAP19-7"
- "CDH9"
- "ZIC4"
- "KRTAP19-2"
- "LCE3E"
- "BRINP3"
- "KIF2B"
- "DEFB110"
- "HMGA2"
- "COX7B2"
- "LLCFC1"
- "OR8H3"
- "KRTAP15-1"
- "TRIM48"
- "OR2T12"
- "CD1A"
- "DUSP22"
- "XCL2"
- "OR5J2"
- "OR2L2"
- "SPRR2B"
- "RPL10L"
- "ST6GAL2"
- "FBXL7"
- "LRFN5"
- "INSL5"
- "FERD3L"
- "TLR4"
- "TAS2R1"
- "FAM47B"
- "PRDM9"
- "LRRTM4"
- "KRTAP21-1"
- "CPXCR1"
- "ST6GALNAC3"
- "DCDC1"
- "CDKN2A"
- "EPHA3"
- "KRTAP23-1"
- "OR5W2"
- "GABRG2"
- "PLPPR4"
- "HAMP"
- "OR2B11"
- "CD1E"
- "LCE1F"
- "TRIM51"
- "SNAP25"
- "RGS4"
- "U2AF1"
- "CDH18"
- "ZNF804A"
- "DKK2"
- "CD5L"
- "LRRC4C"
- "PAK5"
- "SPATA8"
- "UMOD"
- "POTEG"
- "LCE3A"
- "DEFB115"
- "INHBA"
- "OR2T34"
- "SNURF"
- "DCAF12L2"
- "SLITRK2"
- "KCNJ12"
- "OR5T3"
- "BRAF"
- "SPRR2D"
- "OCA2"
- "NTM"
- "BIRC8"
- "ZNF536"
- "ZIC1"
- "GYPC"
- "HBB"
- "STK19"
- "CALN1"
- "HBD"
- "FCER1A"
- "RIPPLY2"
- "SERPINB4"
- "GABRG3"
- "EPHA5"
- "OR4L1"
- "NRXN3"
- "MUC7"
- "DCSTAMP"
- "RTL3"
- "AMELX"
- "GABRA2"
- "DUSP26"
- "VGLL3"
- "KRTAP13-3"
- "TYR"
- "CTNNA2"
- "HGF"
- "OR2T1"
- "OR2M4"
- "HCN1"
- "TSLP"
- "KCNJ3"
- "CUX1"
- "CDH12"
- "RBFOX1"
- "OR4K2"
- "LCE1C"
- "MAGEA4"
- "CLEC3A"
- "TCF21"
- "PSG6"
- "SYNDIG1"
- "GALNT13"
- "MS4A4A"
- "GPX5"
- "NTRK3"
- "PABPC5"
- "FTMT"
- "TPK1"
- "OR51F2"
- "NELL1"
- "CRISP3"
- "KLHL1"
- "HOXA5"
- "SPTA1"
- "OR5M11"
- "STATH"
- "NMUR2"
- "DRD2"
- "MAGEA12"
- "OR5D13"
- "KRTAP6-3"
- "LHX8"
- "SLC8A1"
- "HAPLN1"
- "OR2W3"
- "TAC1"
- "SLITRK1"
- "NLRP3"
- "FAM71B"
- "SPATA19"
- "HTR5A"
- "SPRR3"
- "CACNG3"
- "GLYAT"
- "TNR"
- "DEFB119"
- "KCNK2"
- "TBX5"
- "DCAF12L1"
- "TRIM58"
- "GBA3"
- "MNDA"
- "PCDH15"
- "VSTM2A"
- "GRM8"
- "OR4P4"
- "CDH7"
- "CETN1"
- "RIT2"
- "PDHA2"
- "KRTAP13-1"
- "GABRA5"
- "RIT1"
- "ZSCAN1"
- "VEGFC"
- "ASTN1"
- "BLID"
- "SLC39A12"
- "ADGRL3"
- "LAIR2"
- "CD1C"
- "AG1478"
- "AST1306"
- "AZ-628"
- "Canertinib"
- "Dabrafenib"
- "Dacomitinib"
- "Erlotinib"
- "GDC-0879"
- "Gefitinib"
- "HG-14-8-02"
- "HG-5-88-01"
- "Ischemin"
- "JNJ 26854165"
- "L-779450"
- "Lapatinib"
- "PLX-4720"
- "Pelitinib"
- "RAF 265"
- "SB590885"
- "Sorafenib"
- "Vemurafenib"
- "WZ4002"
