ndex:
  network: a16b5ca0-f6a3-11e8-aaa6-0ac135e8bacf
search_terms:
- "ABCD4"
- "ADGRA2"
- "AES"
- "AFDN"
- "AFF2"
- "AGMO"
- "AGTR2"
- "AHNAK2"
- "AIM2"
- "AKAIN1"
- "AKAP9"
- "AKT1"
- "AKT2"
- "ALK"
- "AMD1"
- "APOA5"
- "ARID1A"
- "ARID1B"
- "ARMC10"
- "ARMC12"
- "ARMCX6"
- "ASXL1"
- "ASXL2"
- "ATR"
- "ATXN7L3"
- "BAP1"
- "BAX"
- "BDKRB2"
- "BEX3"
- "CACNA2D3"
- "CASP8"
- "CBFB"
- "CCDC78"
- "CCER1"
- "CCND3"
- "CD99"
- "CDH1"
- "CDKN1B"
- "CDKN2A"
- "CHEK2"
- "COA6"
- "COL12A1"
- "COL22A1"
- "COL6A3"
- "COX18"
- "CTCF"
- "CTNNA3"
- "DCAF4L2"
- "DNAH11"
- "DNAH5"
- "DTWD2"
- "EGFR"
- "EP300"
- "ERBB2"
- "ERBB3"
- "ERBB4"
- "ESR1"
- "FAM20C"
- "FANCA"
- "FANCD2"
- "FBXW7"
- "FERD3L"
- "FHIT"
- "FOXA1"
- "FOXO3"
- "FOXP1"
- "FRG1"
- "GATA3"
- "GH1"
- "GLDC"
- "GLRX5"
- "GPR32"
- "GPS2"
- "GREM2"
- "HIST1H2AK"
- "HIST1H2BB"
- "HIST1H2BC"
- "HIST1H2BD"
- "HIST1H3B"
- "HIST1H3G"
- "HIST1H4D"
- "HIST2H2AC"
- "HIST2H2BE"
- "HRAS"
- "HS6ST1"
- "IFNGR2"
- "JAK1"
- "KAAG1"
- "KDM6A"
- "KIAA0319"
- "KLK7"
- "KLRC1"
- "KMT2C"
- "KRAS"
- "KRTAP13-4"
- "KRTAP19-6"
- "L1CAM"
- "LAMA2"
- "LAMB3"
- "LCE1E"
- "LDLRAP1"
- "LENEP"
- "LGALS1"
- "LHCGR"
- "LIFR"
- "LIPI"
- "MAGEA8"
- "MAP2K4"
- "MAP3K1"
- "MAP3K13"
- "MEN1"
- "MMP16"
- "MT1X"
- "MXRA7"
- "MYH9"
- "MYO1A"
- "MYO3A"
- "NCOR1"
- "NCOR2"
- "NDUFS2"
- "NF1"
- "NOTCH1"
- "NPNT"
- "NQO1"
- "NRG3"
- "NRXN2"
- "OAZ3"
- "OR2M3"
- "OR5AN1"
- "OSR2"
- "PDE4DIP"
- "PIK3CA"
- "PIK3R1"
- "PILRB"
- "POLR2H"
- "PPIL1"
- "PRKACG"
- "PRKCQ"
- "PRR16"
- "PTEN"
- "PTH2"
- "PTPN22"
- "PTPRD"
- "PTPRM"
- "RB1"
- "RHOA"
- "RHOB"
- "ROS1"
- "RPL19"
- "RUNX1"
- "RYR2"
- "SCAMP3"
- "SETD1A"
- "SF3B1"
- "SGCD"
- "SH2D2A"
- "SH3BGRL3"
- "SHANK2"
- "SHOC2"
- "SIK1"
- "SMAD4"
- "SPAG11B"
- "SPRR2B"
- "ST8SIA3"
- "STAB2"
- "STK11"
- "STK19"
- "SVBP"
- "TAF1"
- "TAL2"
- "TBL1XR1"
- "TBX3"
- "TDO2"
- "TDP2"
- "TDRP"
- "TG"
- "TGIF2LX"
- "THADA"
- "THSD7A"
- "TMED8"
- "TMEM256"
- "TMSB15A"
- "TP53"
- "TPRKB"
- "TTYH1"
- "U2AF1"
- "UQCR10"
- "URB1-AS1"
- "USH2A"
- "USP28"
- "UTRN"
- "VGLL3"
- "WASHC3"
- "ZFP36L1"
- "ZFP64"
- "ZNF200"
- "ZNF415"
- "(-)-Blebbistatin"
- "(Z)-4-Hydroxytamoxifen"
- "A443654"
- "A66"
- "AG1478"
- "ALK-IN-1"
- "AS-252424"
- "AS605240"
- "ASP3026"
- "AST1306"
- "AT-7519"
- "AT7867"
- "AZ 20"
- "AZD 5438"
- "AZD-6482"
- "AZD5363"
- "AZD7762"
- "Afatinib"
- "Alisertib"
- "Alpelisib"
- "Alvocidib"
- "Anacardic acid"
- "BI-2536"
- "BMS-536924"
- "Barasertib"
- "Baricitinib"
- "Bosutinib"
- "Buparlisib"
- "C646"
- "CAL-101"
- "CG-930"
- "CGK733"
- "CH5424802"
- "CP724714"
- "CTB"
- "CUDC-907"
- "Cabozantinib"
- "Canertinib"
- "Cediranib"
- "Ceritinib"
- "Chk2 inhibitor II"
- "Crizotinib"
- "Dacomitinib"
- "Dactolisib"
- "Dasatinib"
- "Dovitinib"
- "Enzastaurin"
- "Erlotinib"
- "Fedratinib"
- "Filgotinib"
- "Foretinib"
- "GDC-0980"
- "GM6001"
- "GSK 690693"
- "GSK-J1"
- "GSK-J4"
- "GSK1059615"
- "GSK1070916"
- "GSK1838705A"
- "Garcinol"
- "Gefitinib"
- "Go 6976"
- "H-8"
- "H89"
- "HG-14-10-04"
- "HG-14-8-02"
- "HG-5-88-01"
- "HG-6-64-01"
- "HG-9-91-01"
- "Ibrutinib"
- "Ipatasertib"
- "KIN001-111"
- "KIN001-135"
- "KW2449"
- "LY294002"
- "Lapatinib"
- "Lestaurtinib"
- "Linsitinib"
- "MK 1775"
- "MK2206"
- "ML-9"
- "MRT67307"
- "Mocetinostat"
- "Momelotinib"
- "NU7441"
- "NVP-BGT226"
- "NVP-TAE226"
- "NVP-TAE684"
- "Neratinib"
- "Nintedanib"
- "Nutlin 3a"
- "Omipalisib"
- "PF-06463922"
- "PF562271"
- "PHA-767491"
- "PI103"
- "PI3K-IN-1"
- "PIK-93"
- "PKC412"
- "PLX-4720"
- "PP1"
- "Palbociclib"
- "Pazopanib"
- "Pelitinib"
- "Pictilisib"
- "Poziotinib"
- "R406"
- "RO 31-8220"
- "Resveratrol"
- "Rigosertib"
- "Ro 32-0432"
- "Ruxolitinib"
- "S-Ruxolitinib"
- "SNS-032"
- "SP600125"
- "Sigma A6730"
- "Sotrastaurin"
- "Staurosporine"
- "Staurosporine aglycone"
- "Sunitinib"
- "TAK-715"
- "TPCA-1"
- "Taselisib"
- "Tofacitinib"
- "Torin1"
- "Torin2"
- "Tozasertib"
- "Trichostatin A"
- "Triciribine"
- "VE-821"
- "Vandetanib"
- "Vorinostat"
- "WH-4-023"
- "WH-4-025"
- "WZ-4-145"
- "WZ4002"
- "XL019"
- "XL147"
- "XL765"
- "XMD11-50"
- "Y-27632"
- "ZM-447439"
- "ZSTK474"
