ndex:
  network: a16b5ca0-f6a3-11e8-aaa6-0ac135e8bacf
search_terms:
- "TP53"
- "PIK3CA"
- "GATA3"
- "CBFB"
- "CDH1"
- "PTEN"
- "MAP2K4"
- "AKT1"
- "RUNX1"
- "TBX3"
- "MAP3K1"
- "CDKN1B"
- "HIST1H3B"
- "KRAS"
- "MYO1A"
- "GPS2"
- "PIK3R1"
- "ZFP36L1"
- "HIST1H2BC"
- "CTCF"
- "FOXA1"
- "GH1"
- "LGALS1"
- "DCAF4L2"
- "RB1"
- "KRTAP13-4"
- "KAAG1"
- "AGMO"
- "CASP8"
- "ERBB2"
- "KLRC1"
- "AKAIN1"
- "KMT2C"
- "FHIT"
- "HIST1H3G"
- "SMAD4"
- "LAMB3"
- "COL22A1"
- "AHNAK2"
- "SF3B1"
- "GPR32"
- "BAP1"
- "TAL2"
- "ARID1A"
- "FERD3L"
- "RPL19"
- "GREM2"
- "TTYH1"
- "STK11"
- "CTNNA3"
- "PDE4DIP"
- "TDRP"
- "CCER1"
- "ERBB3"
- "FBXW7"
- "TMSB15A"
- "TG"
- "URB1-AS1"
- "CD99"
- "FOXO3"
- "PRKCQ"
- "PRKACG"
- "SHANK2"
- "MAGEA8"
- "NCOR1"
- "PILRB"
- "NPNT"
- "AES"
- "THADA"
- "NOTCH1"
- "VGLL3"
- "PPIL1"
- "FAM20C"
- "PTH2"
- "ZFP64"
- "ESR1"
- "BAX"
- "DNAH11"
- "AFF2"
- "ARMC12"
- "PRR16"
- "LDLRAP1"
- "MXRA7"
- "FRG1"
- "TMED8"
- "MYH9"
- "NRXN2"
- "GLDC"
- "ALK"
- "APOA5"
- "SCAMP3"
- "STK19"
- "SHOC2"
- "DTWD2"
- "IFNGR2"
- "RHOB"
- "ARMCX6"
- "HIST1H2BD"
- "NQO1"
- "HIST2H2BE"
- "COA6"
- "CCND3"
- "HIST1H2BB"
- "ZNF200"
- "HIST2H2AC"
- "MYO3A"
- "RHOA"
- "OSR2"
- "EGFR"
- "HRAS"
- "USP28"
- "NF1"
- "TGIF2LX"
- "TBL1XR1"
- "AIM2"
- "TPRKB"
- "AGTR2"
- "GLRX5"
- "ASXL2"
- "AMD1"
- "MEN1"
- "KDM6A"
- "KLK7"
- "KRTAP19-6"
- "LIFR"
- "AFDN"
- "ASXL1"
- "PTPRD"
- "OAZ3"
- "OR2M3"
- "MAP3K13"
- "LCE1E"
- "CDKN2A"
- "RYR2"
- "STAB2"
- "MT1X"
- "COL6A3"
- "SPAG11B"
- "ATXN7L3"
- "LENEP"
- "FANCA"
- "SGCD"
- "ROS1"
- "HIST1H4D"
- "NCOR2"
- "HIST1H2AK"
- "LAMA2"
- "THSD7A"
- "KIAA0319"
- "UQCR10"
- "USH2A"
- "U2AF1"
- "POLR2H"
- "ERBB4"
- "FOXP1"
- "ATR"
- "WASHC3"
- "FANCD2"
- "CACNA2D3"
- "HS6ST1"
- "SETD1A"
- "UTRN"
- "AKT2"
- "ADGRA2"
- "CHEK2"
- "PTPRM"
- "AKAP9"
- "SVBP"
- "ARID1B"
- "SIK1"
- "BEX3"
- "COX18"
- "DNAH5"
- "ZNF415"
- "TDP2"
- "OR5AN1"
- "ABCD4"
- "TDO2"
- "ST8SIA3"
- "JAK1"
- "ARMC10"
- "COL12A1"
- "TMEM256"
- "NDUFS2"
- "BDKRB2"
- "TAF1"
- "SH2D2A"
- "MMP16"
- "L1CAM"
- "PTPN22"
- "LIPI"
- "NRG3"
- "LHCGR"
- "CCDC78"
- "EP300"
- "SH3BGRL3"
- "SPRR2B"
- "(Z)-4-Hydroxytamoxifen"
- "A443654"
- "A66"
- "AG1478"
- "AST1306"
- "AT7867"
- "Afatinib"
- "Alpelisib"
- "Anacardic acid"
- "Buparlisib"
- "C646"
- "CH5424802"
- "CP724714"
- "CTB"
- "Canertinib"
- "Dacomitinib"
- "Erlotinib"
- "GSK 690693"
- "GSK1059615"
- "Garcinol"
- "Gefitinib"
- "HG-14-10-04"
- "HG-14-8-02"
- "HG-5-88-01"
- "HG-9-91-01"
- "Ipatasertib"
- "Ischemin"
- "JNJ 26854165"
- "Lapatinib"
- "MK2206"
- "Momelotinib"
- "NVP-TAE684"
- "Neratinib"
- "Omipalisib"
- "PI103"
- "Pelitinib"
- "Pictilisib"
- "Ruxolitinib"
- "Sigma A6730"
- "Triciribine"
- "WZ4002"
- "XL147"
- "ZSTK474"
