ndex:
  network: ef58f76d-f6a2-11e8-aaa6-0ac135e8bacf
search_terms:
- "ABTB1"
- "ANG"
- "AP3S2"
- "AQP5"
- "ARL3"
- "ASXL1"
- "ATP6V1G3"
- "AURKC"
- "B3GALT5"
- "BRCC3"
- "BRINP3"
- "BRMS1"
- "C4BPB"
- "CACNG2"
- "CADM2"
- "CALR"
- "CAPS"
- "CARD18"
- "CBFB"
- "CBL"
- "CBX5"
- "CBX7"
- "CCDC24"
- "CCDC32"
- "CCL11"
- "CCL16"
- "CCL20"
- "CCL21"
- "CD320"
- "CD70"
- "CD74"
- "CDC42"
- "CEBPA"
- "CFAP300"
- "CFHR2"
- "CHIC2"
- "CLDN11"
- "CLDN14"
- "CLDN18"
- "CRISPLD1"
- "CTSG"
- "DAOA"
- "DAZAP2"
- "DCTD"
- "DDX41"
- "DESI1"
- "DIO2"
- "DIS3"
- "DLX3"
- "DNMT3A"
- "DRD2"
- "DUOXA2"
- "DUSP26"
- "EED"
- "EGFL8"
- "ELANE"
- "EPGN"
- "ETFRF1"
- "ETV6"
- "EZH2"
- "FAM19A4"
- "FAM57B"
- "FLT3"
- "GALNT18"
- "GATA2"
- "GBP4"
- "GCLM"
- "GJB3"
- "GJB4"
- "GPX2"
- "GREM2"
- "GSTK1"
- "GSTM3"
- "GUCA2A"
- "GZMB"
- "HADH"
- "HIST1H3D"
- "HNRNPK"
- "HSPB7"
- "IDH1"
- "IDH2"
- "IL32"
- "ILDR1"
- "IMMP2L"
- "JAM2"
- "KCNE3"
- "KCNK13"
- "KIT"
- "KLK7"
- "KLRK1"
- "KRAS"
- "KRTAP10-8"
- "LCE1B"
- "MAX"
- "MDFI"
- "MED21"
- "MSRB1"
- "MT-ATP6"
- "MT-CO1"
- "MT-CO2"
- "MT-CO3"
- "MT-CYB"
- "MT-ND1"
- "MT-ND5"
- "MYEOV"
- "MYF5"
- "NAPA"
- "NAT8L"
- "NCCRP1"
- "NIPSNAP1"
- "NMNAT2"
- "NMUR2"
- "NOTCH2NLA"
- "NPM1"
- "NPM2"
- "NR2E1"
- "NRAS"
- "NRXN3"
- "OR2AG1"
- "OR2M3"
- "OR3A2"
- "OR51L1"
- "OR5AR1"
- "OR5W2"
- "OR6B2"
- "OR7D4"
- "ORAI1"
- "P2RY2"
- "PDC"
- "PDCD2L"
- "PDCL3"
- "PHACTR1"
- "PHF6"
- "PIP4P2"
- "PKIB"
- "PLA2G2D"
- "PLPP1"
- "POLR2E"
- "PPIC"
- "PTPN11"
- "RAB15"
- "RAB17"
- "RAB23"
- "RAB25"
- "RAB5IF"
- "RAD21"
- "RAP1B"
- "RBBP4"
- "RBKS"
- "RCAN2"
- "REC114"
- "RFC3"
- "RIT1"
- "RPL32"
- "RPL6"
- "RPL9"
- "RPS3A"
- "RUNX1"
- "SBSPON"
- "SLPI"
- "SMC1A"
- "SMC3"
- "SPDYA"
- "SPRR4"
- "SRSF2"
- "SSSCA1"
- "STAG2"
- "STC2"
- "STX3"
- "SULT1B1"
- "SULT1C2"
- "SUMO2"
- "SUZ12"
- "TCL1A"
- "TCTE3"
- "TET2"
- "TFAM"
- "TMCO5A"
- "TMEM18"
- "TMEM231"
- "TMEM47"
- "TNNC2"
- "TP53"
- "TPRG1"
- "TRA2B"
- "TRIM48"
- "TSPAN2"
- "TUBA3C"
- "U2AF1"
- "UBE2R2"
- "UQCC1"
- "UQCR10"
- "USB1"
- "WAC"
- "WT1"
- "ZFP42"
- "ZNF788P"
- "AC220"
- "ALW-II-38-3"
- "ALW-II-49-7"
- "AT9283"
- "AZD7762"
- "Amuvatinib"
- "Axitinib"
- "Azacitidine"
- "BAY61-3606"
- "BIX 02565"
- "BMS 777607"
- "BMS-536924"
- "BX-912"
- "Barasertib"
- "Bortezomib"
- "Bosutinib"
- "Brivanib"
- "Cabozantinib"
- "Cediranib"
- "Celecoxib"
- "Crizotinib"
- "DCC-2036"
- "Dasatinib"
- "Decitabine"
- "Doramapimod"
- "Dorsomorphin"
- "Dovitinib"
- "Entospletinib"
- "Enzastaurin"
- "Erlotinib"
- "Fedratinib"
- "Filgotinib"
- "Foretinib"
- "GSK1070916"
- "GSK461364"
- "GTPL6019"
- "GW843682X"
- "Go 6976"
- "HG-14-10-04"
- "Imatinib"
- "KIN001-269"
- "KW2449"
- "Ki20227"
- "Lestaurtinib"
- "Linifanib"
- "MLN8054"
- "Masitinib"
- "Motesanib"
- "NMS-1286937"
- "NSC-87877"
- "NVP-TAE226"
- "NVP-TAE684"
- "Nilotinib"
- "Nintedanib"
- "Nutlin 3a"
- "OSI-930"
- "PF562271"
- "PHA-665752"
- "PKC412"
- "PP1"
- "PRT062607"
- "Pacritinib"
- "Pazopanib"
- "Ponatinib"
- "R406"
- "RAF 265"
- "Regorafenib"
- "Resveratrol"
- "SGI-1776"
- "Saracatinib"
- "Sorafenib"
- "Staurosporine"
- "Sulindac sulfide"
- "Sunitinib"
- "Tivozanib"
- "Tozasertib"
- "URMC-099"
- "Vandetanib"
- "WZ3105"
- "XL019"
