search_terms:
- "NPM1"
- "NRAS"
- "FLT3"
- "DNMT3A"
- "IDH1"
- "IDH2"
- "KRAS"
- "TP53"
- "RUNX1"
- "CEBPA"
- "U2AF1"
- "WT1"
- "MT-CO2"
- "PHF6"
- "UQCR10"
- "PTPN11"
- "PKIB"
- "SPRR4"
- "ZNF788P"
- "CARD18"
- "ETFRF1"
- "CBFB"
- "SUMO2"
- "CCL20"
- "CCL11"
- "KCNE3"
- "GSTK1"
- "TET2"
- "TCL1A"
- "GUCA2A"
- "MSRB1"
- "ATP6V1G3"
- "LCE1B"
- "CCL16"
- "KIT"
- "RAD21"
- "MT-CYB"
- "MT-CO3"
- "SLPI"
- "CCL21"
- "RPL32"
- "GJB3"
- "HIST1H3D"
- "RAB5IF"
- "FAM57B"
- "TMEM18"
- "FAM19A4"
- "MED21"
- "PLA2G2D"
- "ANG"
- "CD74"
- "MT-ND5"
- "BRINP3"
- "DAOA"
- "EPGN"
- "MAX"
- "TNNC2"
- "CHIC2"
- "DAZAP2"
- "DESI1"
- "GREM2"
- "HSPB7"
- "SMC3"
- "SMC1A"
- "IMMP2L"
- "RFC3"
- "DCTD"
- "PDCD2L"
- "TMEM47"
- "ARL3"
- "RAP1B"
- "CCDC32"
- "P2RY2"
- "CBX5"
- "CDC42"
- "GPX2"
- "RPL9"
- "NR2E1"
- "CD70"
- "AP3S2"
- "PHACTR1"
- "RCAN2"
- "TCTE3"
- "SSSCA1"
- "STAG2"
- "KCNK13"
- "NMUR2"
- "CLDN11"
- "CALR"
- "TRIM48"
- "RBBP4"
- "POLR2E"
- "DUSP26"
- "PPIC"
- "SRSF2"
- "RAB17"
- "RAB15"
- "RAB25"
- "GBP4"
- "NPM2"
- "KLRK1"
- "EED"
- "CADM2"
- "RIT1"
- "TSPAN2"
- "DRD2"
- "ETV6"
- "CBL"
- "MT-ATP6"
- "GSTM3"
- "TUBA3C"
- "HNRNPK"
- "IL32"
- "NOTCH2NLA"
- "GATA2"
- "UBE2R2"
- "RAB23"
- "CLDN14"
- "PDCL3"
- "ABTB1"
- "SUZ12"
- "PDC"
- "EZH2"
- "TFAM"
- "BRMS1"
- "GZMB"
- "MDFI"
- "NRXN3"
- "CBX7"
- "CRISPLD1"
- "CTSG"
- "MT-CO1"
- "C4BPB"
- "KLK7"
- "MYF5"
- "PIP4P2"
- "KRTAP10-8"
- "CLDN18"
- "GJB4"
- "RPS3A"
- "SBSPON"
- "REC114"
- "AQP5"
- "ELANE"
- "USB1"
- "CFAP300"
- "CFHR2"
- "GCLM"
- "DIO2"
- "ILDR1"
- "CAPS"
- "NCCRP1"
- "TPRG1"
- "CD320"
- "PLPP1"
- "NIPSNAP1"
- "EGFL8"
- "TRA2B"
- "RPL6"
- "DLX3"
- "ASXL1"
- "TMCO5A"
- "STX3"
- "NAPA"
- "SULT1B1"
- "SULT1C2"
- "UQCC1"
- "JAM2"
- "ORAI1"
- "STC2"
- "NAT8L"
- "GALNT18"
- "NMNAT2"
- "CCDC24"
- "AURKC"
- "DDX41"
- "OR5AR1"
- "MYEOV"
- "ZFP42"
- "B3GALT5"
- "OR5W2"
- "OR7D4"
- "HADH"
- "OR2M3"
- "OR6B2"
- "SPDYA"
- "BRCC3"
- "OR51L1"
- "OR2AG1"
- "TMEM231"
- "MT-ND1"
- "DIS3"
- "DUOXA2"
- "CACNG2"
- "OR3A2"
- "RBKS"
- "WAC"
- "AC220"
- "Dovitinib"
- "Ischemin"
- "JNJ 26854165"
- "KW2449"
- "Linifanib"
- "Masitinib"
- "OSI-930"
- "Regorafenib"
